services:
    _defaults:
        autowire: true
        autoconfigure: true

    MarcinOrlowski\DiscoToolbar\:
        resource: '../../src/'
        exclude: '../../src/{DependencyInjection,Dto}'

    MarcinOrlowski\DiscoToolbar\Service\DiscoToolbarService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    MarcinOrlowski\DiscoToolbar\Twig\DiscoToolbarExtension:
        tags: ['twig.extension']
